
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //


// convenience file to include all diffusivity models


    #include "diffusivityModel.H"
    #include "fixedDiffusivity.H"
    #include "knudsen.H"
    #include "fsgMolecularWeights.H"
    #include "fsgDiffusionVolumes.H"
    #include "binaryFSG.H"
    #include "porousFSG.H"

// ************************************************************************* //

