#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#------------------------------------------------------------------------------
echo 'Cleaning backup files'
find . \( -name 'VTK' \) -exec rm -rf {} \;
##find . \( -name '[1-9]*' \) -exec rm -rf {} \;
find . \( -name 'output' \) -exec rm {} \;
find . \( -name '*.dat' -o -name '*.log' \) -exec rm {} \;
find . \( -name 'cellToRegion' \) -exec rm {} \;
find . \( -name '*RegionAddressing' \) -exec rm {} \;
find ./0 \( -name 'polyMesh' \) -exec rm -rf {} \;
rm -rf [1-9]*
rm logs > /dev/null 2>&1
rm testLoopReport > /dev/null 2>&1
rm -rf proc_*

echo ''

#foamCleanTutorials cases
cleanCase
rm -rf constant/cbp/polyMesh
rm -rf constant/cathodeFluid/polyMesh
rm -rf constant/electrolyte/polyMesh
rm -rf constant/anodeFluid/polyMesh
rm -rf constant/abp/polyMesh
# ----------------------------------------------------------------- end-of-file
